using System;

namespace KleeneStar.Portal.WebDomain
{
    /// <summary>
    /// A single entry in an issue's conversation timeline. Maps onto the core
    /// <c>Comment</c> entity for human messages and onto a synthetic system note for
    /// machine narration of state changes, share and watch events, and resolution events.
    /// </summary>
    public sealed class IssueComment
    {
        /// <summary>
        /// Gets or sets the comment id.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the comment author. <c>null</c> for system entries.
        /// </summary>
        public IssueParticipant Author { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this entry was generated by the system
        /// (status changes, share events, watch events) and should be styled distinctly
        /// from human messages.
        /// </summary>
        public bool IsSystem { get; set; }

        /// <summary>
        /// Gets or sets the role label rendered next to the author name (e.g.
        /// <c>"Anfragesteller"</c> or <c>"Service Desk"</c>).
        /// </summary>
        public string Role { get; set; }

        /// <summary>
        /// Gets or sets the visibility of the comment. <c>"public"</c> is visible to the
        /// requester, the service team, and everyone the issue is shared with;
        /// <c>"internal-team"</c> is limited to the assigned service group plus the
        /// requester.
        /// </summary>
        public string Visibility { get; set; } = "public";

        /// <summary>
        /// Gets or sets the timestamp at which the entry was created.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the message body. May contain plain text or simple markup.
        /// </summary>
        public string Text { get; set; }
    }
}
