<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>0.0.3.0</Version>
		<AssemblyVersion>0.0.3.0</AssemblyVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/kleenestar-project/KleeneStar.Portal</RepositoryUrl>
		<EnableDynamicLoading>true</EnableDynamicLoading>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\KleeneStar.Core\src\KleeneStar.Core\KleeneStar.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets/**/*.*">
			<LogicalName>$(MSBuildProjectName).Assets.%(RecursiveDir)%(Filename)%(Extension)</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Internationalization\de" />
		<EmbeddedResource Include="Internationalization\en" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
	</ItemGroup>

</Project>
